const STYLE_ID = "mycelium-grove-styles";

const CSS_TEXT =
  '.mycelium-grove-root {\n  width: 100%;\n  height: 100%;\n  position: relative;\n  overflow: hidden;\n  contain: layout paint size;\n  font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, "Apple Color Emoji", "Segoe UI Emoji";\n}\n\n.mycelium-grove-scene {\n  position: relative;\n  width: 100%;\n  height: 100%;\n  overflow: hidden;\n  background-size: cover;\n  background-position: center;\n  background-repeat: no-repeat;\n  image-rendering: pixelated;\n}\n\n.mycelium-grove-layer {\n  position: absolute;\n  inset: 0;\n}\n\n.mycelium-grove-agent {\n  position: absolute;\n  transform: translate(-50%, -100%);\n  transition: left 500ms linear, top 500ms linear;\n  user-select: none;\n  pointer-events: none;\n}\n\n.mycelium-grove-agent__sprite {\n  display: block;\n  image-rendering: pixelated;\n}\n\n.mycelium-grove-agent--bloom .mycelium-grove-agent__sprite { width: 88px; height: auto; }\n.mycelium-grove-agent--worker .mycelium-grove-agent__sprite { width: 84px; height: auto; }\n.mycelium-grove-agent--planner .mycelium-grove-agent__sprite { width: 120px; height: auto; }\n.mycelium-grove-agent--auditor .mycelium-grove-agent__sprite { width: 115px; height: auto; }\n\n.mycelium-grove-agent__label {\n  margin-top: 2px;\n  text-align: center;\n  font-size: 12px;\n  color: rgba(255, 255, 255, 0.92);\n  text-shadow: 0 1px 2px rgba(0, 0, 0, 0.8);\n}\n\n.mycelium-grove-bubble {\n  position: absolute;\n  transform: translate(-50%, -165%);\n  max-width: 180px;\n  padding: 6px 8px;\n  color: rgba(20, 20, 20, 0.95);\n  border-radius: 10px;\n  font-size: 12px;\n  line-height: 1.2;\n  box-shadow: 0 6px 14px rgba(0, 0, 0, 0.18);\n  overflow: hidden;\n  white-space: nowrap;\n  text-overflow: ellipsis;\n  pointer-events: none;\n}\n\n.mycelium-grove-bubble--speech {\n  background: rgba(255, 255, 255, 0.95);\n}\n\n.mycelium-grove-bubble--speech::after {\n  content: "";\n  position: absolute;\n  left: 50%;\n  bottom: -6px;\n  width: 0;\n  height: 0;\n  border: 6px solid transparent;\n  border-top-color: rgba(255, 255, 255, 0.95);\n  transform: translateX(-50%);\n}\n\n.mycelium-grove-bubble--thought {\n  background: rgba(255, 255, 255, 0.92);\n  border-radius: 14px;\n}\n\n.mycelium-grove-bubble--thought::after,\n.mycelium-grove-bubble--thought::before {\n  content: "";\n  position: absolute;\n  left: 50%;\n  background: rgba(255, 255, 255, 0.92);\n  border-radius: 999px;\n  transform: translateX(-50%);\n}\n\n.mycelium-grove-bubble--thought::after {\n  width: 8px;\n  height: 8px;\n  bottom: -12px;\n}\n\n.mycelium-grove-bubble--thought::before {\n  width: 5px;\n  height: 5px;\n  bottom: -20px;\n  opacity: 0.9;\n}';

export function ensureGroveStyles(): void {
  if (document.getElementById(STYLE_ID)) return;

  const style = document.createElement("style");
  style.id = STYLE_ID;
  style.type = "text/css";
  style.appendChild(document.createTextNode(CSS_TEXT));
  document.head.appendChild(style);
}
